### ISSUE TITLE
Graphics - Changing Backgrounds

### ISSUE THREAD

**Issue by on5li7** [on5li7/final-project-group-4#3]
By using the ACM program, I would implement background changes for the rooms of the mansion. I would also include arrows for each room that moves the player to a different room when clicked on. For example, the game starts in the dining hall, and the player can either choose to move to the kitchen, study, armory, or greenhouse. If the player is in the wine cellar, they can only move to the kitchen. Since the move() functions allow the player to move though different rooms too, there will be visual representations of "bus stops" on the map and in certain rooms.

**Comment by onzfonz** [comment]
I like this, but please put these background names into a text file that then gets read in, so that you don't have to spend your time typing out the backgrounds in the code, but come up with a systematic way to process all of those background changes, etc.
